### ISSUE TITLE
Always restarting laravel and queue containers

### ISSUE THREAD

**Issue by fleader64** [EvilFreelancer/laravel-lighthouse-example#2]
I have clone project. Make all actions in unit "1. Preparation". After "docker compose up -d" command I have "laravel" and  "queue" containers which are always restarting. I saw logs in these containers and they have same error: "PHP Fatal error:  Uncaught Error: Class 'Illuminate\Foundation\Application' not found in /app/bootstrap/app.php:14"

**Comment by EvilFreelancer** [comment]
Hello! Yes, seems I mixed some steps in the readme :) thanks for the PR btw

**Comment by EvilFreelancer** [comment]
Readme updated, now instruction is correct, thank you for noticing the error!
